export const EXCLUSIVE_REQUEST = 'EXCLUSIVE_REQUEST'
export const EXCLUSIVE_SUCCESS = 'EXCLUSIVE_SUCCESS'
export const EXCLUSIVE_FAIL = 'EXCLUSIVE_FAIL'

export const COMMENT_REQUEST = 'COMMENT_REQUEST'
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS'
export const COMMENT_FAIL = 'COMMENT_FAIL'

export const SOCIAL_MEDIA_REQUEST = 'SOCIAL_MEDIA_REQUEST'
export const SOCIAL_MEDIA_SUCCESS = 'SOCIAL_MEDIA_SUCCESS'
export const SOCIAL_MEDIA_FAIL = 'SOCIAL_MEDIA_FAIL'

export const PAYMENT_METHOD_REQUEST = 'PAYMENT_METHOD_REQUEST'
export const PAYMENT_METHOD_SUCCESS = 'PAYMENT_METHOD_SUCCESS'
export const PAYMENT_METHOD_FAIL = 'PAYMENT_METHOD_FAIL'

export const MOBILE_STORE_REQUEST = 'MOBILE_STORE_REQUEST'
export const MOBILE_STORE_SUCCESS = 'MOBILE_STORE_SUCCESS'
export const MOBILE_STORE_FAIL = 'MOBILE_STORE_FAIL'

export const COVER_IMAGE_REQUEST = 'COVER_IMAGE_REQUEST'
export const COVER_IMAGE_SUCCESS = 'COVER_IMAGE_SUCCESS'
export const COVER_IMAGE_FAIL = 'COVER_IMAGE_FAIL'

export const ICON_IMAGE_REQUEST = 'ICON_IMAGE_REQUEST'
export const ICON_IMAGE_SUCCESS = 'ICON_IMAGE_SUCCESS'
export const ICON_IMAGE_FAIL = 'ICON_IMAGE_FAIL'

export const STATIC_DATA_REQUEST = 'STATIC_DATA_REQUEST'
export const STATIC_DATA_SUCCESS = 'STATIC_DATA_SUCCESS'
export const STATIC_DATA_FAIL = 'STATIC_DATA_FAIL'

export const TOKEN_UPLOAD_REQUEST = 'TOKEN_UPLOAD_REQUEST'
export const TOKEN_UPLOAD_SUCCESS = 'TOKEN_UPLOAD_SUCCESS'
export const TOKEN_UPLOAD_FAIL = 'TOKEN_UPLOAD_FAIL'

export const TOKEN_DELETE_REQUEST = 'TOKEN_DELETE_REQUEST'
export const TOKEN_DELETE_SUCCESS = 'TOKEN_DELETE_SUCCESS'
export const TOKEN_DELETE_FAIL = 'TOKEN_DELETE_FAIL'


