export const PICKUP_POINTS_REQUEST = 'PICKUP_POINTS_REQUEST';
export const PICKUP_POINTS_SUCCESS = 'PICKUP_POINTS_SUCCESS';
export const PICKUP_POINTS_FAIL = 'PICKUP_POINTS_FAIL';

export const SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS'
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD'
