# Generated by Django 4.0.3 on 2022-03-10 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_image_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExlusiveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.exclusive')),
            ],
        ),
    ]
