# Generated by Django 4.0.3 on 2022-03-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_exclusive_exlusiveimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSupported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='ExlusiveImage',
            new_name='ExclusiveImage',
        ),
    ]
