# Generated by Django 4.0.3 on 2022-04-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_review_rating_review_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
    ]
