# Generated by Django 4.0.3 on 2022-04-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_certificate_image_alter_creditcard_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
